logging:
  level:
    br.com.ilegra.api: DEBUG
    org.springframework.boot.context: DEBUG
server:
  compression:
    enabled: true
  port: 8081
  servlet: 
    context-path: /controle-vendas
management:
  server:
    port: 9091
  endpoints:
    web:
      exposure:
        include: '*'
spring:
  messages:
    basename: i18n/messages
